
name = "DashCoolComponents"
uuid = "1b08a953-4be3-4667-9a23-ce71f4bd3486"
authors = ["Luiz Tauffer, Vinicius Camozzato Vaz and Raul Ros√° <vinicvaz.dev@gmail.com>"]
version = "0.1.3"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compact]
julia = "1.2"
Dash = ">=0.1"
